name: Build and Push Docker Image
on:
  create:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Récupère le nom du tag à partir de la référence
      - name: Get tag name
        id: tag
        run: |
          echo "::set-output name=name::${GITHUB_REF#refs/tags/}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/home-k8s-metadata:${{ steps.tag.outputs.name }}
      - name: Check image
        run: echo "Image ghcr.io/${{ github.repository }}/home-k8s-metadata:${{ steps.tag.outputs.name }} a été poussée avec succès."